version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  backend:
    build: .
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/static/
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    volumes:
      - static_volume:/static/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - certbot_volume:/etc/letsencrypt/
      - certbot_volume:/var/www/certbot/
    networks:
      - app_network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_volume:/etc/letsencrypt/
      - certbot_volume:/var/www/certbot/
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${SSL_EMAIL} -d ${DOMAIN} --agree-tos
    depends_on:
      - nginx
    networks:
      - app_network

volumes:
  db_data:
  static_volume:
  certbot_volume: